openapi: 3.0.1
info:
  title: EmailsController OpenApi specification
  version: 0.0.1
paths:
  /api/emails:
    get:
      tags:
      - EmailsController
      operationId: listEmails
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmailDto'
    post:
      tags:
      - EmailsController
      operationId: createEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmailDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailDto'
  /api/emails/{id}:
    put:
      tags:
      - EmailsController
      operationId: updateEmail
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmailDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailDto'
    delete:
      tags:
      - EmailsController
      operationId: deleteEmail
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "204":
          description: OK
components:
  schemas:
    EmailDto:
      type: object
    CreateEmailDto:
      type: object
    UpdateEmailDto:
      type: object
