openapi: 3.0.1
info:
  title: UsersController OpenApi specification
  version: 0.0.1
paths:
  /api/users:
    get:
      tags:
      - UsersController
      operationId: listUsers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      required:
      - id
      - name
