openapi: 3.0.1
info:
  title: fixme
  version: v1
paths:
  /api/users:
    get:
      tags:
      - UsersController
      operationId: listUsers
      responses:
        "200":
          description: fixme
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'
components:
  schemas:
    List:
      type: object
